imports:
    - { resource: "services/form.yml" }
    - { resource: "services/gateway_factory.yml" }
    - { resource: "services/action.yml" }
    - { resource: "services/validators.yml" }
    - { resource: "services/repository.yml" }

services:
    bitbag_sylius_quadpay_plugin.quadpay_api_client:
        class: BitBag\SyliusQuadPayPlugin\Client\QuadPayApiClient
        public: true
        arguments:
            - "@sylius.http_client"

    bitbag_sylius_quadpay_plugin.payment_processing.refund:
        class: BitBag\SyliusQuadPayPlugin\PaymentProcessing\RefundPaymentProcessor
        public: true
        arguments:
            - "@session"
            - "@bitbag_sylius_quadpay_plugin.quadpay_api_client"

    bitbag_sylius_quadpay_plugin.resolver.payment_state:
        class: BitBag\SyliusQuadPayPlugin\Resolver\PaymentStateResolver
        arguments:
            - "@sm.factory"
            - "@bitbag_sylius_quadpay_plugin.quadpay_api_client"
            - "@sylius.manager.payment"

    bitbag_sylius_quadpay_plugin.command.payment_state:
        class: BitBag\SyliusQuadPayPlugin\Command\UpdatePaymentStateCommand
        arguments:
            - "@bitbag_sylius_quadpay_plugin.rapository.payment"
            - "@bitbag_sylius_quadpay_plugin.resolver.payment_state"
            - "@monolog.logger"
        tags:
            - { name: console.command }

    bitbag_sylius_quadpay_plugin.twig.extension.block:
        class: BitBag\SyliusQuadPayPlugin\Twig\Extension\RenderWidgetExtension
        arguments:
            - "@bitbag_sylius_quadpay_plugin.rapository.payment_method"
            - "@templating"
        tags:
            - { name: twig.extension }
